import { supabase } from '../lib/supabase';
import type { Settings, BackupData } from '../types';

const DEFAULT_SETTINGS: Settings = { id: 'settings', myPersonId: null, theme: 'light' };
export async function getSettings(): Promise<Settings> { const { data, error } = await supabase.from('app_settings').select('*').eq('id', 'settings').maybeSingle(); if (error) throw error; return (data as Settings | null) ?? DEFAULT_SETTINGS; }
export async function updateSettings(patch: Partial<Settings>): Promise<Settings> { const updated = { ...(await getSettings()), ...patch, id: 'settings' as const }; const { error } = await supabase.from('app_settings').upsert(updated); if (error) throw error; return updated; }
export async function exportData(): Promise<BackupData> { const [persons, debts, payments, settings] = await Promise.all([supabase.from('persons').select('*'), supabase.from('debts').select('*'), supabase.from('payments').select('*'), getSettings()]); for (const result of [persons, debts, payments]) if (result.error) throw result.error; return { version: 1, exportedAt: new Date().toISOString(), persons: (persons.data ?? []) as BackupData['persons'], debts: (debts.data ?? []) as BackupData['debts'], payments: (payments.data ?? []) as BackupData['payments'], settings }; }
export function downloadBackup(data: BackupData): void { const blob = new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' }); const url = URL.createObjectURL(blob); const a = document.createElement('a'); a.href = url; a.download = 'debt-tracker-backup.json'; document.body.appendChild(a); a.click(); a.remove(); URL.revokeObjectURL(url); }
export function validateBackup(data: unknown): data is BackupData { if (!data || typeof data !== 'object') return false; const d = data as Record<string, unknown>; return Array.isArray(d.persons) && Array.isArray(d.debts) && Array.isArray(d.payments) && typeof d.settings === 'object' && d.settings !== null; }
export async function importData(data: BackupData): Promise<void> { await resetAllData(); const people = await supabase.from('persons').insert(data.persons); if (people.error) throw people.error; const debts = await supabase.from('debts').insert(data.debts); if (debts.error) throw debts.error; const payments = await supabase.from('payments').insert(data.payments); if (payments.error) throw payments.error; const settings = await supabase.from('app_settings').upsert({ ...data.settings, id: 'settings' }); if (settings.error) throw settings.error; }
export async function resetAllData(): Promise<void> { const [payments, debts, persons] = await Promise.all([supabase.from('payments').delete().neq('id', ''), supabase.from('debts').delete().neq('id', ''), supabase.from('persons').delete().neq('id', '')]); for (const result of [payments, debts, persons]) if (result.error) throw result.error; const settings = await supabase.from('app_settings').delete().eq('id', 'settings'); if (settings.error) throw settings.error; }